function Hd = myfir_kaiser_50N_60_600_Hz
%MYFIR_KAISER_50N_60_600_HZ Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.3 and the DSP System Toolbox 8.6.
% Generated on: 03-Apr-2017 19:39:26

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 10000;  % Sampling Frequency

N    = 50;       % Order
Fc1  = 400;       % First Cutoff Frequency
Fc2  = 600;      % Second Cutoff Frequency
flag = 'scale';  % Sampling Flag
Beta = 5;      % Window Parameter
% Create the window vector for the design algorithm.
win = kaiser(N+1, Beta);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, [Fc1 Fc2]/(Fs/2), 'bandpass', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
